- name: Instalar k3s server en master
  hosts: master
  become: true

  tasks:
    - name: Instalar dependencias mínimas
      apt:
        name:
          - curl
        state: present
        update_cache: true

    - name: Instalar k3s server en nodo único
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        creates: /etc/systemd/system/k3s.service

    - name: Asegurar que k3s está arrancado
      service:
        name: k3s
        state: started
        enabled: true

    - name: Copiar kubeconfig a usuario david
      shell: |
        mkdir -p /home/david/.kube
        cp /etc/rancher/k3s/k3s.yaml /home/david/.kube/config
        chown -R david:david /home/david/.kube

